version: '3.8'
services:
  vue-app:
    container_name: cali-girl-notary
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build
