name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - name: Checkout source
      uses: actions/checkout@v2  # Checks out the repository under $GITHUB_WORKSPACE.

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Sets up Node.js version 16.

    - name: Install Bun
      run: curl https://bun.sh/install | bash  # Installs Bun.

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.bun/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      run: bun install  # Installs dependencies using Bun.

    - name: Build
      run: bun run build  # Builds the site using the specified script in package.json.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Directory to deploy.
